// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Data;

#nullable disable

namespace Persistence.Data.Migrations
{
    [DbContext(typeof(PushUpNikeContext))]
    [Migration("20231214174917_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Domain.Entities.CarritoCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdCarritoCompra");

                    b.Property<int>("CantidadCadaProductoEnCarrito")
                        .HasColumnType("int")
                        .HasColumnName("CantidadCadaProductoEnCarrito");

                    b.Property<int>("IdClienteFk")
                        .HasColumnType("int")
                        .HasColumnName("IdClienteFk");

                    b.Property<int>("IdProductoFk")
                        .HasColumnType("int")
                        .HasColumnName("IdProductoFk");

                    b.Property<double>("PrecioTotalCarrito")
                        .HasColumnType("double")
                        .HasColumnName("PrecioTotalCarrito");

                    b.Property<string>("ProductoEnCarrito")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar")
                        .HasColumnName("ProductoEnCarrito");

                    b.HasKey("Id");

                    b.HasIndex("IdClienteFk");

                    b.HasIndex("IdProductoFk");

                    b.ToTable("CarritoCompra", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CantidadCadaProductoEnCarrito = 2,
                            IdClienteFk = 1,
                            IdProductoFk = 1,
                            PrecioTotalCarrito = 20.5,
                            ProductoEnCarrito = "Producto 1"
                        },
                        new
                        {
                            Id = 2,
                            CantidadCadaProductoEnCarrito = 1,
                            IdClienteFk = 1,
                            IdProductoFk = 3,
                            PrecioTotalCarrito = 15.75,
                            ProductoEnCarrito = "Producto 2"
                        },
                        new
                        {
                            Id = 3,
                            CantidadCadaProductoEnCarrito = 3,
                            IdClienteFk = 2,
                            IdProductoFk = 2,
                            PrecioTotalCarrito = 30.0,
                            ProductoEnCarrito = "Producto 3"
                        },
                        new
                        {
                            Id = 4,
                            CantidadCadaProductoEnCarrito = 1,
                            IdClienteFk = 3,
                            IdProductoFk = 1,
                            PrecioTotalCarrito = 10.0,
                            ProductoEnCarrito = "Producto 4"
                        },
                        new
                        {
                            Id = 5,
                            CantidadCadaProductoEnCarrito = 2,
                            IdClienteFk = 2,
                            IdProductoFk = 3,
                            PrecioTotalCarrito = 25.5,
                            ProductoEnCarrito = "Producto 5"
                        });
                });

            modelBuilder.Entity("Domain.Entities.CategoriaProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdCategoriaProducto");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar")
                        .HasColumnName("Nombre");

                    b.HasKey("Id");

                    b.ToTable("CategoriaProducto", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Jackets"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "T-Shirts"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Pants"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdCliente");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("Apellidos");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar")
                        .HasColumnName("Direccion");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("Nombres");

                    b.Property<double>("NroContacto")
                        .HasColumnType("double")
                        .HasColumnName("NroContacto");

                    b.HasKey("Id");

                    b.ToTable("Cliente", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellidos = "Castro Torres",
                            Direccion = "Calle 15, Bucaramanga",
                            Nombres = "Diego Fernando",
                            NroContacto = 3115411220.0
                        },
                        new
                        {
                            Id = 2,
                            Apellidos = "Aristizabal",
                            Direccion = "Carrera 23, Piedecuesta",
                            Nombres = "Jennifer",
                            NroContacto = 3115422110.0
                        },
                        new
                        {
                            Id = 3,
                            Apellidos = "Castro Torres",
                            Direccion = "Calle 25, Giron",
                            Nombres = "Alexandra",
                            NroContacto = 3118473642.0
                        });
                });

            modelBuilder.Entity("Domain.Entities.ClienteCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdClienteCompra");

                    b.Property<string>("DireccionCliente")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar")
                        .HasColumnName("DireccionCliente");

                    b.Property<DateTime>("FechaTransaccion")
                        .HasColumnType("DateTime")
                        .HasColumnName("FechaTransaccion");

                    b.Property<int>("IdClienteFk")
                        .HasColumnType("int")
                        .HasColumnName("IdClienteFk");

                    b.Property<int>("IdCompraFk")
                        .HasColumnType("int")
                        .HasColumnName("IdCompraFk");

                    b.Property<int>("IdMetodoPagoFk")
                        .HasColumnType("int")
                        .HasColumnName("IdMetodoPagoFk");

                    b.Property<double>("ValorTotalTransaccion")
                        .HasColumnType("double")
                        .HasColumnName("ValorTotalTransaccion");

                    b.HasKey("Id");

                    b.HasIndex("IdClienteFk");

                    b.HasIndex("IdCompraFk");

                    b.HasIndex("IdMetodoPagoFk");

                    b.ToTable("ClienteCompra", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DireccionCliente = "Calle A, Ciudad",
                            FechaTransaccion = new DateTime(2023, 12, 14, 12, 49, 17, 348, DateTimeKind.Local).AddTicks(323),
                            IdClienteFk = 1,
                            IdCompraFk = 1,
                            IdMetodoPagoFk = 1,
                            ValorTotalTransaccion = 50.0
                        },
                        new
                        {
                            Id = 2,
                            DireccionCliente = "Calle B, Ciudad",
                            FechaTransaccion = new DateTime(2023, 12, 14, 12, 49, 17, 348, DateTimeKind.Local).AddTicks(339),
                            IdClienteFk = 2,
                            IdCompraFk = 2,
                            IdMetodoPagoFk = 2,
                            ValorTotalTransaccion = 75.0
                        },
                        new
                        {
                            Id = 3,
                            DireccionCliente = "Calle C, Ciudad",
                            FechaTransaccion = new DateTime(2023, 12, 14, 12, 49, 17, 348, DateTimeKind.Local).AddTicks(340),
                            IdClienteFk = 3,
                            IdCompraFk = 3,
                            IdMetodoPagoFk = 1,
                            ValorTotalTransaccion = 100.0
                        });
                });

            modelBuilder.Entity("Domain.Entities.Compra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdCompra");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("Cantidad");

                    b.Property<int>("IdProductoFk")
                        .HasColumnType("int")
                        .HasColumnName("IdProductoFk");

                    b.Property<double>("ValorUnitUSD")
                        .HasColumnType("double")
                        .HasColumnName("ValorUnitUSD");

                    b.HasKey("Id");

                    b.HasIndex("IdProductoFk");

                    b.ToTable("Compra", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cantidad = 3,
                            IdProductoFk = 1,
                            ValorUnitUSD = 20.0
                        },
                        new
                        {
                            Id = 2,
                            Cantidad = 2,
                            IdProductoFk = 2,
                            ValorUnitUSD = 15.5
                        },
                        new
                        {
                            Id = 3,
                            Cantidad = 1,
                            IdProductoFk = 3,
                            ValorUnitUSD = 30.0
                        });
                });

            modelBuilder.Entity("Domain.Entities.DetalleProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdDetalleProducto");

                    b.Property<string>("DetallesAdicionalesProducto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar")
                        .HasColumnName("DetallesAdicionalesProducto");

                    b.Property<int>("IdProductoFk")
                        .HasColumnType("int")
                        .HasColumnName("IdProductoFk");

                    b.HasKey("Id");

                    b.HasIndex("IdProductoFk");

                    b.ToTable("DetalleProducto", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DetallesAdicionalesProducto = "Detalles adicionales para Producto 1",
                            IdProductoFk = 1
                        },
                        new
                        {
                            Id = 2,
                            DetallesAdicionalesProducto = "Detalles adicionales para Producto 2",
                            IdProductoFk = 2
                        },
                        new
                        {
                            Id = 3,
                            DetallesAdicionalesProducto = "Detalles adicionales para Producto 3",
                            IdProductoFk = 3
                        });
                });

            modelBuilder.Entity("Domain.Entities.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdPago");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("Nombre");

                    b.HasKey("Id");

                    b.ToTable("Pago", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Tarjeta de Crédito"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Transferencia Bancaria"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "PayPal"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Efectivo"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Cheque"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Tarjeta de Débito"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdProducto");

                    b.Property<int>("IdCategoriaFk")
                        .HasColumnType("int")
                        .HasColumnName("IdCategoriaFk");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("Marca");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar")
                        .HasColumnName("Nombre");

                    b.Property<double>("Precio")
                        .HasColumnType("double")
                        .HasColumnName("Precio");

                    b.Property<int>("StockDisponible")
                        .HasColumnType("int")
                        .HasColumnName("StockDisponible");

                    b.Property<string>("UrlImagen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar")
                        .HasColumnName("UrlImagen");

                    b.HasKey("Id");

                    b.HasIndex("IdCategoriaFk");

                    b.ToTable("Producto", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdCategoriaFk = 1,
                            Marca = "Nike",
                            Nombre = "Abrigo 01",
                            Precio = 1000.0,
                            StockDisponible = 10,
                            UrlImagen = "aa"
                        },
                        new
                        {
                            Id = 2,
                            IdCategoriaFk = 2,
                            Marca = "Nike",
                            Nombre = "Camiseta 01",
                            Precio = 500.0,
                            StockDisponible = 100,
                            UrlImagen = "aa"
                        },
                        new
                        {
                            Id = 3,
                            IdCategoriaFk = 3,
                            Marca = "Nike",
                            Nombre = "Pantalon 01",
                            Precio = 1200.0,
                            StockDisponible = 30,
                            UrlImagen = "aa"
                        });
                });

            modelBuilder.Entity("Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Revoked")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Token")
                        .HasColumnType("longtext");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("RefreshToken", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdRol");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("NombreRol");

                    b.HasKey("Id");

                    b.ToTable("Rol", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Gerente"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Empleado"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Persona"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_Usuario");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar")
                        .HasColumnName("Email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar")
                        .HasColumnName("Password");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar")
                        .HasColumnName("Username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Usuario", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "fercho11422@gmail.com",
                            Password = "123456",
                            Username = "Diego Castro"
                        },
                        new
                        {
                            Id = 2,
                            Email = "jennifer@gmail.com",
                            Password = "1234567",
                            Username = "Jennifer Aristizabal"
                        },
                        new
                        {
                            Id = 3,
                            Email = "alexandra@gmail.com",
                            Password = "1234568",
                            Username = "Alexandra Castro"
                        });
                });

            modelBuilder.Entity("Domain.Entities.UsuarioRoles", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("UsuarioId", "RolId");

                    b.HasIndex("RolId");

                    b.ToTable("UsuarioRoless");
                });

            modelBuilder.Entity("Domain.Entities.CarritoCompra", b =>
                {
                    b.HasOne("Domain.Entities.Cliente", "Clientes")
                        .WithMany("CarritoCompras")
                        .HasForeignKey("IdClienteFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Producto", "Productos")
                        .WithMany("CarritoCompras")
                        .HasForeignKey("IdProductoFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clientes");

                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Domain.Entities.ClienteCompra", b =>
                {
                    b.HasOne("Domain.Entities.Cliente", "Clientes")
                        .WithMany("ClienteCompras")
                        .HasForeignKey("IdClienteFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Compra", "Compras")
                        .WithMany("ClienteCompras")
                        .HasForeignKey("IdCompraFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Pago", "Pagos")
                        .WithMany("ClienteCompras")
                        .HasForeignKey("IdMetodoPagoFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clientes");

                    b.Navigation("Compras");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("Domain.Entities.Compra", b =>
                {
                    b.HasOne("Domain.Entities.Producto", "Productos")
                        .WithMany("Compras")
                        .HasForeignKey("IdProductoFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Domain.Entities.DetalleProducto", b =>
                {
                    b.HasOne("Domain.Entities.Producto", "Productos")
                        .WithMany("DetalleProductos")
                        .HasForeignKey("IdProductoFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Domain.Entities.Producto", b =>
                {
                    b.HasOne("Domain.Entities.CategoriaProducto", "CategoriaProductos")
                        .WithMany("Productos")
                        .HasForeignKey("IdCategoriaFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriaProductos");
                });

            modelBuilder.Entity("Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Domain.Entities.Usuario", "Usuario")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.Entities.UsuarioRoles", b =>
                {
                    b.HasOne("Domain.Entities.Rol", "Roles")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Usuario", "Usuarios")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Roles");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Domain.Entities.CategoriaProducto", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Domain.Entities.Cliente", b =>
                {
                    b.Navigation("CarritoCompras");

                    b.Navigation("ClienteCompras");
                });

            modelBuilder.Entity("Domain.Entities.Compra", b =>
                {
                    b.Navigation("ClienteCompras");
                });

            modelBuilder.Entity("Domain.Entities.Pago", b =>
                {
                    b.Navigation("ClienteCompras");
                });

            modelBuilder.Entity("Domain.Entities.Producto", b =>
                {
                    b.Navigation("CarritoCompras");

                    b.Navigation("Compras");

                    b.Navigation("DetalleProductos");
                });

            modelBuilder.Entity("Domain.Entities.Rol", b =>
                {
                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UsuarioRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
